# values.yaml

grafana:
  enabled: true
  adminPassword: "your-secure-password"
  service:
    type: LoadBalancer  # expose grafana externally
  ingress:
    enabled: false

prometheus:
  prometheusSpec:
    replicas: 2  # High Availability
    retention: 15d
    resources:
      requests:
        memory: 400Mi
      limits:
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
  additionalRules:
    - name: example
      groups:
        - name: example-rules
          rules:
            - alert: HighPodCPU
              expr: sum(rate(container_cpu_usage_seconds_total{container!="",pod!=""}[5m])) by (pod) > 0.8
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: "High CPU usage detected"
                description: "Pod {{ $labels.pod }} is using >80% CPU for 2 minutes."


alertmanager:
  alertmanagerSpec:
    replicas: 2
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: 'default-receiver'
    receivers:
      - name: 'default-receiver'
        email_configs:
          - to: 'your-team@example.com'
            send_resolved: true
