name: Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-k8s:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      EKS_CLUSTER: your-eks-cluster-name

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::<account-id>:role/github-actions-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER

    - name: Deploy Kubernetes manifests
      run: |
        kubectl apply -f task3/backend/manifests
        kubectl apply -f task3/frontend/manifests
