name: Terraform Plan

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::<account-id>:role/github-actions-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      working-directory: task2/
      run: terraform init

    - name: Terraform Validate
      working-directory: task2/
      run: terraform validate

    - name: Terraform Plan
      working-directory: task2/
      run: terraform plan
