apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DATABASE_URL: "postgres://username:password@db-endpoint:5432/dbname" # this should be kept in a secret manager instead or the value should be updated through a CI/CD pipeline
