apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
type: Opaque
stringData:
  aws_access_key_id: YOUR_AWS_ACCESS_KEY_ID # use from a secure place like Secret Manager
  aws_secret_access_key: YOUR_AWS_SECRET_ACCESS_KEY # use from a secure place like Secret Manager
